OpenConext/Stepup-RA

composer.json
composer.lock
src/Security/Firewall/SamlListener.php

https://www.pivotaltracker.com/story/show/86891136

Ensure InResponseTo between request and response matches

---

composer.json
composer.lock

Required for two things:
- Being able to set the subject on Saml Requests
- Update the metadata signing algorithm to SHA256

Update SAML2 and saml-bundle

---

app/AppKernel.php
app/Resources/translations/messages.en_GB.xliff
app/Resources/translations/messages.nl_NL.xliff
app/Resources/translations/validators.en_GB.xliff
app/Resources/translations/validators.nl_NL.xliff
app/Resources/views/base.html.twig
app/config/config.yml
composer.json
composer.lock
src/Command/SearchRaSecondFactorsCommand.php
src/Controller/SecondFactorController.php
src/Form/Type/SearchRaSecondFactorsType.php
src/Resources/config/routing.yml
src/Resources/config/services.yml
src/Resources/public/less/style.less
src/Resources/views/Pagination/sortable_link.html.twig
src/Resources/views/SecondFactor/search.html.twig
src/Resources/views/translations.html.twig
src/Service/RaSecondFactorService.php

List and search second factors

---

app/Resources/translations/messages.en_GB.xliff
app/Resources/translations/messages.nl_NL.xliff
app/Resources/translations/validators.en_GB.xliff
app/Resources/translations/validators.nl_NL.xliff
app/Resources/views/base.html.twig
composer.lock
src/Surfnet/StepupRa/RaBundle/Command/RevokeSecondFactorCommand.php
src/Surfnet/StepupRa/RaBundle/Controller/SecondFactorController.php
src/Surfnet/StepupRa/RaBundle/Form/Type/RevokeSecondFactorType.php
src/Surfnet/StepupRa/RaBundle/Resources/config/routing.yml
src/Surfnet/StepupRa/RaBundle/Resources/config/services.yml
src/Surfnet/StepupRa/RaBundle/Resources/public/js/stepup-ra.js
src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less
src/Surfnet/StepupRa/RaBundle/Resources/views/SecondFactor/search.html.twig
src/Surfnet/StepupRa/RaBundle/Service/RaSecondFactorService.php

See https://www.pivotaltracker.com/story/show/79439036

Revoke Second Factors

---

src/Surfnet/StepupRa/RaBundle/Controller/Vetting/SmsController.php
src/Surfnet/StepupRa/RaBundle/Form/Type/VerifyIdentityType.php
src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less
src/Surfnet/StepupRa/RaBundle/Resources/views/Vetting/verifyIdentity.html.twig
src/Surfnet/StepupRa/RaBundle/Service/SmsService.php

See https://www.pivotaltracker.com/story/show/86104444

Change styling of Identity Vetting page

---

composer.json
composer.lock
src/Surfnet/StepupRa/RaBundle/Controller/Vetting/SmsController.php
src/Surfnet/StepupRa/RaBundle/Resources/views/Vetting/Sms/sendChallenge.html.twig
src/Surfnet/StepupRa/RaBundle/Service/VettingService.php

Depends on https://github.com/SURFnet/Stepup-bundle/pull/12

Consistent display of phonenumbers

---

composer.lock
src/Surfnet/StepupRa/RaBundle/Command/StartVettingProcedureCommand.php
src/Surfnet/StepupRa/RaBundle/Controller/VettingController.php
src/Surfnet/StepupRa/RaBundle/Service/VettingService.php
src/Surfnet/StepupRa/RaBundle/VettingProcedure.php

Update vetting per Middleware changes

---

app/Resources/translations/messages.en_GB.xliff
app/Resources/translations/messages.nl_NL.xliff
app/Resources/translations/validators.en_GB.xliff
app/Resources/translations/validators.nl_NL.xliff
src/Surfnet/StepupRa/RaBundle/Controller/Vetting/SmsController.php
src/Surfnet/StepupRa/RaBundle/Resources/views/Vetting/Sms/sendChallenge.html.twig
src/Surfnet/StepupRa/RaBundle/Resources/views/translations.html.twig
src/Surfnet/StepupRa/RaBundle/Service/SmsSecondFactor/OtpVerification.php
src/Surfnet/StepupRa/RaBundle/Service/SmsSecondFactor/SessionSmsVerificationStateHandler.php
src/Surfnet/StepupRa/RaBundle/Service/SmsSecondFactor/SmsVerificationState.php
src/Surfnet/StepupRa/RaBundle/Service/SmsSecondFactor/SmsVerificationStateHandler.php
src/Surfnet/StepupRa/RaBundle/Service/SmsSecondFactorService.php
src/Surfnet/StepupRa/RaBundle/Service/VettingService.php
src/Surfnet/StepupRa/RaBundle/Tests/Service/SmsSecondFactor/SmsVerificationStateTest.php

Somehow lost during rebasing or sth.

Missing SMS request/verification attempt functionality

---

app/Resources/translations/messages.en_GB.xliff
app/Resources/translations/messages.nl_NL.xliff
src/Surfnet/StepupRa/RaBundle/Controller/SecondFactorController.php

Cannot reproduce exception [as described in ticket](https://www.pivotaltracker.com/story/show/90517108). Can reproduce issue with different exception, which this PR addresses.
```
Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException:
"Warning: array_fill(): Number of elements must be positive" at
/var/www/ra-dev.stepup.coin.surf.net/src/Surfnet/StepupRa/RaBundle/Controller/SecondFactorController.php
line 52
```

Don't error when searching tokens returns an empty result set

---

app/Resources/translations/messages.en_GB.xliff
app/Resources/translations/messages.nl_NL.xliff
app/Resources/translations/validators.en_GB.xliff
app/Resources/translations/validators.nl_NL.xliff
composer.json
composer.lock
src/Surfnet/StepupRa/RaBundle/Command/SearchSecondFactorAuditLogCommand.php
src/Surfnet/StepupRa/RaBundle/Controller/SecondFactorController.php
src/Surfnet/StepupRa/RaBundle/Resources/config/routing.yml
src/Surfnet/StepupRa/RaBundle/Resources/config/services.yml
src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less
src/Surfnet/StepupRa/RaBundle/Resources/views/RaManagement/manage.html.twig
src/Surfnet/StepupRa/RaBundle/Resources/views/SecondFactor/auditLog.html.twig
src/Surfnet/StepupRa/RaBundle/Resources/views/SecondFactor/search.html.twig
src/Surfnet/StepupRa/RaBundle/Resources/views/translations.html.twig
src/Surfnet/StepupRa/RaBundle/Service/AuditLogService.php
src/Surfnet/StepupRa/RaBundle/Service/IdentityService.php

Depends on https://github.com/SURFnet/Stepup-Middleware-clientbundle/pull/27

Enable Auditlog in RA

---

app/Resources/translations/messages.en_GB.xliff
app/Resources/translations/messages.nl_NL.xliff
app/Resources/translations/validators.en_GB.xliff
app/Resources/translations/validators.nl_NL.xliff
composer.json
composer.lock
src/Surfnet/StepupRa/RaBundle/Command/AmendRegistrationAuthorityInformationCommand.php
src/Surfnet/StepupRa/RaBundle/Controller/RaManagementController.php
src/Surfnet/StepupRa/RaBundle/Form/Type/AmendRegistrationAuthorityInformationType.php
src/Surfnet/StepupRa/RaBundle/Resources/config/routing.yml
src/Surfnet/StepupRa/RaBundle/Resources/config/services.yml
src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less
src/Surfnet/StepupRa/RaBundle/Resources/views/RaManagement/amendRaInformation.html.twig
src/Surfnet/StepupRa/RaBundle/Resources/views/RaManagement/manage.html.twig
src/Surfnet/StepupRa/RaBundle/Resources/views/translations.html.twig
src/Surfnet/StepupRa/RaBundle/Service/RaService.php

Allow a registration authority's information to be amended

---

app/Resources/translations/messages.en_GB.xliff
app/Resources/translations/messages.nl_NL.xliff
src/Surfnet/StepupRa/RaBundle/Controller/Vetting/GssfController.php
src/Surfnet/StepupRa/RaBundle/Controller/Vetting/SmsController.php
src/Surfnet/StepupRa/RaBundle/Controller/Vetting/YubikeyController.php
src/Surfnet/StepupRa/RaBundle/Controller/VettingController.php
src/Surfnet/StepupRa/RaBundle/Resources/config/routing.yml
src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less
src/Surfnet/StepupRa/RaBundle/Resources/views/Vetting/Gssf/initiate.html.twig
src/Surfnet/StepupRa/RaBundle/Resources/views/Vetting/Sms/provePossession.html.twig
src/Surfnet/StepupRa/RaBundle/Resources/views/Vetting/Sms/sendChallenge.html.twig
src/Surfnet/StepupRa/RaBundle/Resources/views/Vetting/Yubikey/verify.html.twig
src/Surfnet/StepupRa/RaBundle/Resources/views/Vetting/partial/cancelVettingProcedure.html.twig
src/Surfnet/StepupRa/RaBundle/Resources/views/Vetting/verifyIdentity.html.twig
src/Surfnet/StepupRa/RaBundle/Service/VettingService.php

Allow RA to cancel a vetting procedure

---

app/Resources/views/base.html.twig
app/config/config.yml
app/console
app_dev.php.dist
composer.json
composer.lock
src/Surfnet/StepupRa/RaBundle/Form/Extension/InstitutionListingChoiceList.php
src/Surfnet/StepupRa/RaBundle/Form/Extension/RaRoleChoiceList.php
src/Surfnet/StepupRa/RaBundle/Form/Type/AmendRegistrationAuthorityInformationType.php
src/Surfnet/StepupRa/RaBundle/Form/Type/AnchorType.php
src/Surfnet/StepupRa/RaBundle/Form/Type/CreateRaType.php
src/Surfnet/StepupRa/RaBundle/Form/Type/InstitutionSelectionType.php
src/Surfnet/StepupRa/RaBundle/Form/Type/RevokeSecondFactorType.php
src/Surfnet/StepupRa/RaBundle/Form/Type/SearchRaCandidatesType.php
src/Surfnet/StepupRa/RaBundle/Form/Type/SearchRaSecondFactorsType.php
src/Surfnet/StepupRa/RaBundle/Form/Type/SendSmsChallengeType.php
src/Surfnet/StepupRa/RaBundle/Form/Type/StartVettingProcedureType.php
src/Surfnet/StepupRa/RaBundle/Form/Type/VerifyIdentityType.php
src/Surfnet/StepupRa/RaBundle/Form/Type/VerifyPhoneNumberType.php
src/Surfnet/StepupRa/RaBundle/Form/Type/VerifyYubikeyPublicIdType.php

Form choices verified to be in working order.

Upgrade to Symfony 2.7 LTS

---

src/Surfnet/StepupRa/RaBundle/Form/Type/ChangeRaRoleType.php

Use new RaRoleChoiceList::create() method and Symfony 2.7 form options

Use new RaRoleChoiceList::create() method and Symfony 2.7 form options

---

app/Resources/translations/messages.en_GB.xliff
app/Resources/translations/messages.nl_NL.xliff
app/config/config.yml
app/config/parameters.yml.dist
composer.json
composer.lock
src/Surfnet/StepupRa/RaBundle/Controller/Vetting/GssfController.php
src/Surfnet/StepupRa/RaBundle/Controller/Vetting/SecondFactorController.php
src/Surfnet/StepupRa/RaBundle/Controller/Vetting/SmsController.php
src/Surfnet/StepupRa/RaBundle/Controller/Vetting/YubikeyController.php
src/Surfnet/StepupRa/RaBundle/Controller/VettingController.php
src/Surfnet/StepupRa/RaBundle/DependencyInjection/Configuration.php
src/Surfnet/StepupRa/RaBundle/DependencyInjection/SurfnetStepupRaRaExtension.php
src/Surfnet/StepupRa/RaBundle/Resources/views/Vetting/secondFactorTypeDisabled.html.twig
src/Surfnet/StepupRa/RaBundle/Resources/views/translations.html.twig
src/Surfnet/StepupRa/RaBundle/Tests/DependencyInjection/ConfigurationTest.php

RAs are shown a screen informing the second factor type is disabled if
the second factor type is disabled.

Require enabling of second factors

---

app/Resources/translations/messages.en_GB.xliff
app/Resources/translations/messages.nl_NL.xliff
app/Resources/views/base.html.twig
app/config/config.yml
app/config/parameters.yml.dist
src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less

https://www.pivotaltracker.com/projects/1163646/stories/114385851
@rjkip to start your monday morning with 😄

Add footer link to manual with configurable URL

---

src/Surfnet/StepupRa/RaBundle/Resources/views/Vetting/Sms/sendChallenge.html.twig

https://www.pivotaltracker.com/n/projects/1163646/stories/100299518

Put cancel button left and send code button right.

---

src/Surfnet/StepupRa/RaBundle/Controller/Vetting/SmsController.php
src/Surfnet/StepupRa/RaBundle/Form/Type/VerifyPhoneNumberType.php
src/Surfnet/StepupRa/RaBundle/Resources/public/js/stepup-ra.js
src/Surfnet/StepupRa/RaBundle/Resources/views/Vetting/Sms/provePossession.html.twig

https://www.pivotaltracker.com/n/projects/1163646/stories/100299518 task 8 and 9

Prove sms posession button reordering

---

src/Surfnet/StepupRa/RaBundle/Controller/Vetting/SmsController.php
src/Surfnet/StepupRa/RaBundle/Controller/VettingController.php
src/Surfnet/StepupRa/RaBundle/Form/Type/VerifyIdentityType.php
src/Surfnet/StepupRa/RaBundle/Form/Type/VerifyPhoneNumberType.php
src/Surfnet/StepupRa/RaBundle/Resources/public/js/stepup-ra.js
src/Surfnet/StepupRa/RaBundle/Resources/views/Vetting/Sms/provePossession.html.twig
src/Surfnet/StepupRa/RaBundle/Resources/views/Vetting/verifyIdentity.html.twig

https://www.pivotaltracker.com/n/projects/1163646/stories/100299518 points 10, 11 and 12

Verify identity button reordering

---

app/Resources/translations/messages.en_GB.xliff
app/Resources/translations/messages.nl_NL.xliff

[112970535](https://www.pivotaltracker.com/story/show/112970535)

Clarify that button leads to possibility to change a role

---

app/Resources/translations/messages.en_GB.xliff
app/Resources/translations/messages.nl_NL.xliff
src/Surfnet/StepupRa/RaBundle/Form/Type/RetractRegistrationAuthorityType.php

[122116807](https://www.pivotaltracker.com/story/show/122116807)

Translate cancel/confirm buttons when retracting RA

---

.gitignore
app/Resources/views/base.html.twig
app/config/config.yml
app/config/global_view_parameters.yml.dist
app/config/parameters.yml.dist
composer.json
src/Surfnet/StepupRa/RaBundle/Assert.php
src/Surfnet/StepupRa/RaBundle/Exception/AssertionFailedException.php
src/Surfnet/StepupRa/RaBundle/Resources/config/services.yml
src/Surfnet/StepupRa/RaBundle/Service/GlobalViewParameters.php

[131975453](https://www.pivotaltracker.com/story/show/131975453)
This adds global view parameters, allowing multi-locale parameters to be injected in the view.
A multi-locale manual URL is configured in this PR.
SURFnet/Stepup-SelfService#112

RA: Multi locale urls

---

app/Resources/translations/messages.en_GB.xliff
app/Resources/translations/messages.nl_NL.xliff
src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less
src/Surfnet/StepupRa/RaBundle/Resources/views/Vetting/startProcedure.html.twig

[120346189](https://www.pivotaltracker.com/story/show/120346189)

Add translated information texts for starting vetting procedure

---

src/Surfnet/StepupRa/RaBundle/Service/U2fService.php
src/Surfnet/StepupRa/RaBundle/Service/YubikeyService.php

[126126187](https://www.pivotaltracker.com/story/show/126126187)
This correctly implements Guzzle 6 interfaces and uses the shared JsonHelper from the StepupBundle.

Correctly implement Guzzle 6 interfaces

---

app/Resources/translations/messages.en_GB.xliff
app/Resources/translations/messages.nl_NL.xliff
src/Surfnet/StepupRa/RaBundle/Controller/SecondFactorController.php
src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less
src/Surfnet/StepupRa/RaBundle/Resources/views/SecondFactor/search.html.twig

The total number of selected second factor tokens is now displayed right
beneath the search button.

Show search result count

---

app/AppKernel.php
app/Resources/translations/messages.en_GB.xliff
app/Resources/translations/messages.nl_NL.xliff
composer.json
composer.lock
src/Surfnet/StepupRa/RaBundle/Command/ExportRaSecondFactorsCommand.php
src/Surfnet/StepupRa/RaBundle/Controller/SecondFactorController.php
src/Surfnet/StepupRa/RaBundle/Form/Type/SearchRaSecondFactorsType.php
src/Surfnet/StepupRa/RaBundle/Resources/config/services.yml
src/Surfnet/StepupRa/RaBundle/Resources/public/js/stepup-ra.js
src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less
src/Surfnet/StepupRa/RaBundle/Resources/views/SecondFactor/search.html.twig
src/Surfnet/StepupRa/RaBundle/Service/RaSecondFactorExport.php
src/Surfnet/StepupRa/RaBundle/Service/RaSecondFactorService.php

When RAA searched tokens, he/she is now able to export the list of tokens.

Support export of searched tokens

---

.travis.yml
composer.lock

See [Pivotal tracker](https://www.pivotaltracker.com/story/show/156226909) for a description of the problem and a motivation for the solution.
Also see [this commit](https://github.com/OpenConext/Stepup-Middleware-clientbundle/commit/60cc5468d912b5ceb52d4bbf68a5b66ec109ae15) for the actual bugfix in the Stepup-middleware-client-bundle

Bugfix: Validation configuration issue in InstitutionConfigurationOptions

---

app/config/config_dev.yml
app/config/parameters.yml.dist
composer.json
composer.lock

Based on Pieters work in the dev-vm branch, but added some additional commits.

Change dev logging configuration to use syslog instead of graylog

---

app/Resources/translations/messages.en_GB.xliff
app/Resources/translations/messages.nl_NL.xliff
app/Resources/translations/validators.en_GB.xliff
app/Resources/translations/validators.nl_NL.xliff
src/Surfnet/StepupRa/RaBundle/Resources/views/SecondFactor/auditLog.html.twig

See https://www.pivotaltracker.com/story/show/160283521

Show institution information info on audit log

---

src/Surfnet/StepupRa/RaBundle/Command/AccreditCandidateCommand.php
src/Surfnet/StepupRa/RaBundle/Command/SearchRaCandidatesCommand.php
src/Surfnet/StepupRa/RaBundle/Controller/RaManagementController.php
src/Surfnet/StepupRa/RaBundle/Form/Type/SearchRaCandidatesType.php
src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less
src/Surfnet/StepupRa/RaBundle/Resources/views/RaManagement/manage.html.twig
src/Surfnet/StepupRa/RaBundle/Service/RaCandidateService.php

Add updated endpoints to support FGA changes in middleware.
The composer file with the changes for development need to be updated before merge!
See: https://www.pivotaltracker.com/story/show/160283517

Added FGA endpoints for testing Middleware changes

---

src/Surfnet/StepupRa/RaBundle/Command/AmendRegistrationAuthorityInformationCommand.php
src/Surfnet/StepupRa/RaBundle/Controller/RaManagementController.php
src/Surfnet/StepupRa/RaBundle/Service/RaService.php

This PR will allow amending RA information and will
add the RA-institution in the request to middleware.
https://github.com/OpenConext/Stepup-Middleware-clientbundle/pull/67

Allow amending RA info

---

app/config/parameters.yml.dist
app/config/security.yml
src/Surfnet/StepupRa/RaBundle/Resources/config/security.yml
src/Surfnet/StepupRa/RaBundle/Security/Authentication/Handler/LogoutSuccessHandler.php

The logout redirect utrl didn't work. This commit will make sure the
redirect uri will work and adds multilingual support.

Introduce multi-lingual logout redirect

---

src/Surfnet/StepupRa/RaBundle/Command/ExportRaSecondFactorsCommand.php
src/Surfnet/StepupRa/RaBundle/Command/SearchRaSecondFactorsCommand.php
src/Surfnet/StepupRa/RaBundle/Controller/SecondFactorController.php
src/Surfnet/StepupRa/RaBundle/Service/RaSecondFactorService.php

This PR is branched from #193. Review this first

Allow SRAA's to view all tokens

---

app/Resources/translations/messages.en_GB.xliff
app/Resources/translations/messages.nl_NL.xliff
app/Resources/translations/validators.en_GB.xliff
app/Resources/translations/validators.nl_NL.xliff
composer.lock
src/Surfnet/StepupRa/RaBundle/Command/SearchRaListingCommand.php
src/Surfnet/StepupRa/RaBundle/Controller/RaManagementController.php
src/Surfnet/StepupRa/RaBundle/Form/Extension/RaRoleChoiceList.php
src/Surfnet/StepupRa/RaBundle/Form/Type/SearchRaListingType.php
src/Surfnet/StepupRa/RaBundle/Resources/config/services.yml
src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less
src/Surfnet/StepupRa/RaBundle/Resources/views/RaManagement/manage.html.twig
src/Surfnet/StepupRa/RaBundle/Service/RaListingService.php

Searching is possible on name, email, role and ra institution. Changes where also required in the Middleware and the client bundle.

Add search support on the RA management page

---

app/Resources/translations/messages.en_GB.xliff
app/Resources/translations/messages.nl_NL.xliff
app/Resources/translations/validators.en_GB.xliff
app/Resources/translations/validators.nl_NL.xliff
src/Surfnet/StepupRa/RaBundle/Command/SearchRaCandidatesCommand.php
src/Surfnet/StepupRa/RaBundle/Controller/RaManagementController.php
src/Surfnet/StepupRa/RaBundle/Form/Type/SearchRaCandidatesType.php
src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less

On the 'management/search-ra-candidate' page we want to be able to
filter on the institution. That is exactly what is added in this PR/
commit.
https://www.pivotaltracker.com/story/show/163903585

Allow filtering the RA candidate on institute

---

src/Surfnet/StepupRa/RaBundle/Resources/views/Profile/profile.html.twig

Like the other mentions of authorizations throughout the application.
See pivotal: https://www.pivotaltracker.com/story/show/164244620 (task 1)

Show authorizations with @ seperator

---

app/Resources/translations/messages.en_GB.xliff
app/Resources/translations/messages.nl_NL.xliff
app/Resources/translations/validators.en_GB.xliff
app/Resources/translations/validators.nl_NL.xliff
src/Surfnet/StepupRa/RaBundle/Command/AccreditCandidateCommand.php
src/Surfnet/StepupRa/RaBundle/Command/SearchRaListingCommand.php
src/Surfnet/StepupRa/RaBundle/Form/Extension/RaRoleChoiceList.php
src/Surfnet/StepupRa/RaBundle/Form/Type/CreateRaType.php
src/Surfnet/StepupRa/RaBundle/Form/Type/RoleAtInstitutionType.php
src/Surfnet/StepupRa/RaBundle/Form/Type/SearchRaListingType.php
src/Surfnet/StepupRa/RaBundle/Resources/public/js/stepup-ra.js
src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less
src/Surfnet/StepupRa/RaBundle/Service/RaCandidateService.php
src/Surfnet/StepupRa/RaBundle/Service/RaListingService.php
src/Surfnet/StepupRa/RaBundle/Value/RoleAtInstitution.php

To prevent confusion, these elements are rendered next to each other as requested in the wireframes.
Please see individual commit messages for juicy details
More details in Pivotal:
https://www.pivotaltracker.com/story/show/164244268 (task 1)

Align role @ institution form elements horizontally

---

src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less
src/Surfnet/StepupRa/RaBundle/Resources/views/InstitutionConfiguration/overview.html.twig

Two of the three changes described in the [Pivotal bugreport](https://www.pivotaltracker.com/story/show/164244514) are addressed in this PR (1 and 2). See individual commits for details.

Institution config overview tweaks

---

CHANGELOG.md
composer.json
composer.lock

Symfony was upgraded to 3.4.26
Twig was upgraded to 1.39.1

Security upgrades for release 17

---

CHANGELOG.md
composer.lock

Symfony was upgraded to 3.4.26
Twig was upgraded to 1.39.1

Security upgrades for release 16

---

app/Resources/translations/messages.en_GB.xliff
app/Resources/translations/messages.nl_NL.xliff
src/Surfnet/StepupRa/RaBundle/Resources/public/js/stepup-ra.js
src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less

The GUI of the language switcher should be optimized in order to be
more user friendly.
Also prevented submitting the form manually after the selection is changed.

Adjust language switcher GUI

---

app/Resources/translations/messages.en_GB.xliff
app/Resources/translations/messages.nl_NL.xliff
composer.lock
src/Surfnet/StepupRa/RaBundle/Controller/RaLocationController.php
src/Surfnet/StepupRa/RaBundle/Controller/RaaController.php
src/Surfnet/StepupRa/RaBundle/Resources/config/routing.yml
src/Surfnet/StepupRa/RaBundle/Resources/config/services.yml
src/Surfnet/StepupRa/RaBundle/Resources/public/js/stepup-ra.js
src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less
src/Surfnet/StepupRa/RaBundle/Resources/views/InstitutionConfiguration/overview.html.twig
src/Surfnet/StepupRa/RaBundle/Resources/views/Partial/languageSwitcher.html.twig
src/Surfnet/StepupRa/RaBundle/Resources/views/RaLocation/manage.html.twig
src/Surfnet/StepupRa/RaBundle/Service/InstitutionListingService.php

There needs to be a institution switch to switch between
available institutions a user is RAA for.

Add RA institution switcher

---

src/Surfnet/StepupRa/RaBundle/Controller/RaManagementController.php
src/Surfnet/StepupRa/RaBundle/Controller/SecondFactorController.php

The pagination is broken after a KNP pagination bundle update. This can be fixed by setting the total pages manually.
**Also cherrypick into R16**

Fix the missing pagination

---

composer.json
composer.lock

Install recent Symfony security updates
Also pins twig/twig to a compatible version for use with the Mopa Bootstrap bundle.

Security updates

---

CHANGELOG.md

Add the changelog and change some documentation to reflect the changes
after the upgrade to php72 and Symfony 4.4 (Flex)

Add changelog for 4.0.0

---

.travis.yml
package.json
yarn.lock

Upgrade node-forge and object-path (high severity)
https://github.com/advisories/GHSA-92xj-mqp7-vmcj
https://github.com/advisories/GHSA-cwx2-736x-mf6w

Upgrade dependencies

---

.gitignore
.travis.yml
build.xml
composer.json
package.json
yarn.lock

https://github.com/sensiolabs/security-checker is EOL

Move from security-checker to local-php-security-checker

---

src/Surfnet/StepupRa/RaBundle/Resources/views/translations.html.twig
translations/messages.en_GB.xliff
translations/messages.nl_NL.xliff

https://www.pivotaltracker.com/story/show/178241372

Integrate move second factor audit log

---

ci/qa/phplint
ci/qa/security-tests
composer.lock
package.json
yarn.lock

A bit of a hodgepodge PR..
1. Installed Yarn and Composer security upgrades.
1. Updated some of the CI scripts to increase their readability.
1. Added `composer validate` to the phplint qa script.

Install security upgrades

---

translations/messages.nl_NL.xliff

As per: https://www.pivotaltracker.com/story/show/181172862/comments/230294014

Update Dutch deprovision translation

---

ci/qa/phpmd

In the previous Ant script situation this was xml aswell.

Change phpmd parser from text to xml

---

bin/extract-translations.sh
composer.json
composer.lock
templates/institution_configuration/overview.html.twig
translations/messages+intl-icu.en_GB.xliff
translations/messages+intl-icu.nl_NL.xliff
translations/validators+intl-icu.en_GB.xliff
translations/validators+intl-icu.nl_NL.xliff

Todo:
https://github.com/OpenConext/Stepup-RA/issues/444

Show sso registration bypass on institution configuration
