OpenConext/Stepup-RA

- app/Resources/translations/messages.en_GB.xliff
- app/Resources/translations/messages.nl_NL.xliff
- composer.lock
- src/Resources/config/services.yml
- src/Resources/views/Saml/Exception/authnFailed.html.twig
- src/Resources/views/Saml/Exception/noAuthnContext.html.twig
- src/Resources/views/Saml/Exception/preconditionNotMet.html.twig
- src/Security/Firewall/SamlListener.php
- AuthnFailed - IdP failed to authenticate user
- NoAuthnContext - LoA precondition not met
- * - All other cases where preconditions weren't met
The reason the response is rendered and set from the SamlListener and
not from a kernel listener is the fact that the firewall errors out
when the listener doesn't set a token.
> Render informative error screens in case of the below resp. statuses

- app/Resources/translations/validators.en_GB.xliff
- app/Resources/translations/validators.nl_NL.xliff
- src/Surfnet/StepupRa/RaBundle/Command/AccreditCandidateCommand.php
- src/Surfnet/StepupRa/RaBundle/Command/AmendRegistrationAuthorityInformationCommand.php
- src/Surfnet/StepupRa/RaBundle/Resources/public/js/stepup-ra.js
This commit also falls back to native browser form validation behaviour when the form isn't valid at the time the submission modal is to be opened.
> Validate RA creation and amendment forms

- src/Surfnet/StepupRa/RaBundle/Controller/Vetting/GssfController.php
- src/Surfnet/StepupRa/RaBundle/Form/Type/InitiateGssfType.php
- src/Surfnet/StepupRa/RaBundle/Resources/config/services.yml
- src/Surfnet/StepupRa/RaBundle/Resources/views/Vetting/Gssf/initiate.html.twig
Addresses [Security Audit 5.6.1. Check for cross-site request forgery](https://www.pivotaltracker.com/story/show/104421476).
> Check-up resultaat
> 
> Het is nog steeds mogelijk om cross-site request forgery (CSRF) toe te passen binnen de scope van deze test. Dit checklist item is daarom gemarkeerd als ‘Failed’.
>
> Binnen de kwetsbare omgevingen wordt op een aantal plaatsen geen gebruik gemaakt van unieke formulier-tokens. De onderstaande tabel toont de functionaliteiten waar bescherming tegen cross- site request forgery niet is aangetroffen.
> 
> URL Methode
> 
> https://ra.test.surfconext.nl/vetting- POST procedure/d0e7e0ae-bf40-4e79-adc0- 62c84dfb225c/gssf/tiqr/authenticate
> 
> Functionaliteit
> 
> Initiëren Tiqr authenticatie
> 
> Een aanvaller kan deze kwetsbaarheden misbruiken om …
> Use SF form for GSSF initiate action for CSRF protection

- src/Surfnet/StepupRa/RaBundle/Resources/config/services.yml
- src/Surfnet/StepupRa/RaBundle/Service/VettingService.php
Add IdentityService to VettingService and lookup SF identity, use it's locale for translation.
Completely untested but what do you think of injecting the IdentityService in the VettingService @rjkip ?
> Send SMS challenge in registrant locale

- app/Resources/views/base.html.twig
- app/config/config.yml
- build-pre-commit.xml
- src/Surfnet/StepupRa/RaBundle/EventListener/InconsistentStateListener.php
- src/Surfnet/StepupRa/RaBundle/Exception/InconsistentStateException.php
- src/Surfnet/StepupRa/RaBundle/Resources/config/services.yml
- src/Surfnet/StepupRa/RaBundle/Security/Authentication/Provider/SamlProvider.php
- src/Surfnet/StepupRa/RaBundle/Security/Authentication/Token/SamlToken.php
- src/Surfnet/StepupRa/RaBundle/Service/InstitutionConfigurationOptionsService.php
- src/Surfnet/StepupRa/RaBundle/Tests/Security/Authentication/Token/SamlTokenTest.php
- src/Surfnet/StepupRa/RaBundle/Twig/InstitutionConfigurationOptions.php
This PR adds InstitutionConfigurationOptions to the `SamlToken`. The options are set whenever a user has been authenticated and are exposed to Twig via global parameters.
This can only be merged when a stable MiddlewareClientBundle release is required through composer, offering the InstitutionConfigurationOptions API.
_Note: commit history has been rebased to make more sense, yet Github show it chronologically_
> Add institution configuration options

- app/Resources/views/base.html.twig
- src/Surfnet/StepupRa/RaBundle/Controller/SraaController.php
- src/Surfnet/StepupRa/RaBundle/Security/Authentication/Provider/SamlProvider.php
- src/Surfnet/StepupRa/RaBundle/Security/Authentication/Token/SamlToken.php
See [comment](https://www.pivotaltracker.com/story/show/116602125/comments/146521669).
This fixes the issue that, when changing institutions as SRAA, the institution configuration options are used for the SRAAs institution instead of the selected institution.
The left navigation has gotten more room for its components, yet the navigation UI could use some work to allow for expansion of the left or right menu.
> Fix RA locations appearance and token data

- src/Surfnet/StepupRa/RaBundle/Controller/RaManagementController.php
[130522531](https://www.pivotaltracker.com/story/show/130522531)
The issue relates to the page number (the `p` in the query string) being extracted as a string, while, in the `SearchRaCandidatesCommand`, the page number is [expected to be an integer](https://github.com/SURFnet/Stepup-RA/blob/45be0aebb1440d780cc01e42176bebe3aca896e8/src/Surfnet/StepupRa/RaBundle/Command/SearchRaCandidatesCommand.php#L60-L66).
> Convert string to integer when paginating

- app/Resources/translations/messages.nl_NL.xliff
- src/Surfnet/StepupRa/RaBundle/Resources/views/Vetting/Sms/provePossession.html.twig
- src/Surfnet/StepupRa/RaBundle/Resources/views/Vetting/verifyIdentity.html.twig
[130445161](https://www.pivotaltracker.com/story/show/130445161)
[131362893](https://www.pivotaltracker.com/story/show/131362893)
This moves the cancel buttons so the correct action is triggered when pressing enter.
This also fixes a translation issue.
> UI and UX fixes

- src/Surfnet/StepupRa/RaBundle/EventListener/LocaleListener.php
- src/Surfnet/StepupRa/RaBundle/Resources/config/services.yml
- src/Surfnet/StepupRa/RaBundle/Security/Authentication/Handler/ExplicitSessionTimeoutHandler.php
- src/Surfnet/StepupRa/RaBundle/Service/LocaleProviderService.php
[113611545](https://www.pivotaltracker.com/story/show/113611545)
Gateway determines it locale solely based on the identity's SecondFactor. The displayed language is currently determined by the locale of SelfService and RA, which are stored in their sessions. MW/GW don't know about these locales upon entry. Furthermore, GW does not store any state about the identity. This is why the LocaleCookieListener will be implemented in RA and in SelfService.
This implements the locale cookie listener from the StepupBundle into RA.
For its SelfService counter-part, see: [Stepup-SelfService #111](https://github.com/SURFnet/Stepup-SelfService/pull/111).
> Implement locale cookie listener from StepupBundle into RA

- app/config/config.yml
[133251949](https://www.pivotaltracker.com/story/show/133251949)
For forms to come, if there are texts where "(optional)" is required, that can be done in the builder for the form when necessary.
> Remove '(optional)' from forms

- app/Resources/translations/validators.en_GB.xliff
- app/Resources/translations/validators.nl_NL.xliff
- src/Surfnet/StepupRa/RaBundle/Command/VerifyIdentityCommand.php
- src/Surfnet/StepupRa/RaBundle/Form/Type/VerifyIdentityType.php
[86104518](https://www.pivotaltracker.com/story/show/86104518)
In PHP, a constraint has been added to document number input of the verify identity form. 
*EDIT: the validation text has since this image been customised and translated, it will give separate messages for numbers < 1 (if the user somehow manages to post that) and for numbers > 6*
> Restrict document number input to a maximum of six characters

- app/Resources/translations/messages.en_GB.xliff
- app/Resources/translations/messages.nl_NL.xliff
- src/Surfnet/StepupRa/RaBundle/Resources/views/SecondFactor/auditLog.html.twig
[133246727](https://www.pivotaltracker.com/story/show/133246727)
This makes sure the correct ordering names are used to order the audit log by.
This also makes the translation keys for "events" and "second_factor_identifier" less confusing.
SURFnet/Stepup-Middleware#158
> Correct audit log ordering

- app/Resources/translations/messages.en_GB.xliff
- app/Resources/translations/messages.nl_NL.xliff
- app/config/config.yml
- app/config/parameters.yml.dist
- src/Surfnet/StepupRa/RaBundle/Controller/VettingController.php
- src/Surfnet/StepupRa/RaBundle/DependencyInjection/Configuration.php
- src/Surfnet/StepupRa/RaBundle/DependencyInjection/SurfnetStepupRaRaExtension.php
- src/Surfnet/StepupRa/RaBundle/Resources/views/Vetting/verifyIdentity.html.twig
- src/Surfnet/StepupRa/RaBundle/Resources/views/translations.html.twig
- src/Surfnet/StepupRa/RaBundle/Service/VettingService.php
[133015027](https://www.pivotaltracker.com/story/show/133015027)
I have added the rendering of form errors to the verify identity screen. These are pretty generic but the translations could be adapted to convey more clearly what has or could have gone wrong. 
Update: Middleware should communicate its errors more explicitly so that RA could show more clearly what is going on.
> Clear error message when registration code is expired

- app/Resources/translations/messages.en_GB.xliff
- app/Resources/translations/messages.nl_NL.xliff
- src/Surfnet/StepupRa/RaBundle/Controller/VettingController.php
- src/Surfnet/StepupRa/RaBundle/Resources/views/translations.html.twig
- src/Surfnet/StepupRa/RaBundle/Service/VettingService.php
This PR mitigates the issue that RAs can vet registrants with a different institution than they have.
This relates to SURFnet/Stepup-Middleware#160.
At first, I added this check to the final verification step. This was not necessary as we have enough information to stop earlier in the process. This explains the reverted commits. The changes to the domain shall remain, see: SURFnet/Stepup-Middleware#160.
> Communicate error when RA vets outside his institution

- composer.lock
[135780169](https://www.pivotaltracker.com/story/show/135780169)
For an overview of changes between the current and the new SAML2 versions, see the [diff on Github](https://github.com/simplesamlphp/saml2/compare/v1.9...v1.10.3). This includes a security fix and the way SAML2 deals with EPTIs. The latter does not affect RA.
The stepup-saml-bundle has been updated to a hotfix that is functionally identical to the current version, the xmlseclibs have been updated and contain mostly [typo fixes](https://github.com/robrichards/xmlseclibs/compare/1.4.1...1.4.2).
This has been tested by hand.
**Related**
SURFnet/Stepup-SelfService#115
SURFnet/Stepup-Gateway#106
> RA: Update SAML2 dependency

- composer.json
- composer.lock
- src/Surfnet/StepupRa/RaBundle/Service/RaCandidateService.php
This prevents assigning RA(A) rights to users who don't have the correct LoA3 second factor.
Depends on https://github.com/OpenConext/Stepup-Middleware-clientbundle/pull/50
https://www.pivotaltracker.com/story/show/131617617
> Only show RA candidates with verified Loa 3 second factors

- app/AppKernel.php
- app/config/config.yml
- app/config/config_dev.yml
- app/config/config_test.yml
- composer.json
- composer.lock
These are the changes to the RA to lose the SwiftMailer vulnerability. Described in this PivotalTracker ticket [#142301387](https://www.pivotaltracker.com/story/show/142301387).
Note that the solution was to remove the SwiftmailerBundle dependency altogether
> Vulnerability swiftmailer CVE-2016-10074

- src/Surfnet/StepupRa/RaBundle/Controller/VettingController.php
- src/Surfnet/StepupRa/RaBundle/Service/VettingService.php
- src/Surfnet/StepupRa/RaBundle/Tests/Service/VettingServiceTest.php
Instead of showing the expiration error when the vetting process is
almost completed, show it right after looking up the registration
code. This saves time of the user and the RA.
See: https://www.pivotaltracker.com/story/show/133928873
> Show expiration error early in the vetting process

- src/Surfnet/StepupRa/RaBundle/Controller/VettingController.php
This PR makes sure the isGssf method is no longer called on the SeconfFacorType class but on the SFTypeService instead.
This required the installation of version 3.0.0 of the stepup bundle.
See [pivotal](https://www.pivotaltracker.com/story/show/153250034) tracker for more information
> Implement is gssf deprecation

- composer.lock
This upgrade was performed to apply the 'bugfix' described in [Pivotal tracker](https://www.pivotaltracker.com/story/show/153244803).
> Upgrade stepup-middleware-client-bundle to 2.3.1

- src/Surfnet/StepupRa/RaBundle/Controller/Vetting/YubikeyController.php
Error messages on a form element are not translated by default, error
messages on the form itself are. To fix the described issue, we add
error messages on the parent form just like all other errors in RA.
See https://www.pivotaltracker.com/story/show/158660535
> Translate Yubikey OTP error messages

- app_dev.php.dist
When the 'testcookie' is set, Nginx and PHP-fpm will set the APP_DEV
environment variable to 'test'.
If the variable for some reason is not set, the system falls back on the
default 'dev' environment.
See: https://www.pivotaltracker.com/story/show/156570267
> Set Symfony environment from cookie if available

- src/Surfnet/StepupRa/RaBundle/Controller/RaLocationController.php
- src/Surfnet/StepupRa/RaBundle/Controller/RaManagementController.php
- src/Surfnet/StepupRa/RaBundle/Controller/Vetting/SmsController.php
- src/Surfnet/StepupRa/RaBundle/Controller/Vetting/YubikeyController.php
- src/Surfnet/StepupRa/RaBundle/Controller/VettingController.php
The addError construction expects translated messages. The translator
is not available in the controllers and adding extra coupling was
not preferred over changing to flash messages.
See: https://www.pivotaltracker.com/story/show/160228972
> Use flash messages for error messaging

- src/Surfnet/StepupRa/RaBundle/Form/Type/VerifyPhoneNumberType.php
The OptionsResolver works differently in Symfony 3.4. This was not
correctly fixed in the previous commits for the VerifyPhoneNumberType.
The setAllowedTypes method is now called correctly. Preventing issues on
while processing the form.
> Correct the way allowed types are set

- app/config/config_test.yml
- app/config/service_test.yml
- composer.lock
- src/Surfnet/StepupRa/RaBundle/Form/Type/VerifyPhoneNumberType.php
- src/Surfnet/StepupRa/RaBundle/Service/VettingService.php
The test double is used to prevent the sending of actual SMS messages to
a test user.
In order to make the change work correctly, the VettingService now works
with the SmsSecondFactorServiceInterface. This interface will be
introduced in the upcoming Stepup-bundle release.
> Provide Behat support in RA

- CHANGELOG.md
- app/config/config_test.yml
- app/config/service_test.yml
- src/Surfnet/StepupRa/RaBundle/Tests/TestDouble/Factory/GuzzleApiFactory.php
In order to use the middleware api in test mode, guzzle needs to be
configured to pass along the testcookie. Otherwise middleware will
not know it is dealing with a test call.
See: https://www.pivotaltracker.com/story/show/160318902
> Override the middleware api clients for smoke tests

- src/Surfnet/StepupRa/RaBundle/Controller/SecondFactorController.php
- src/Surfnet/StepupRa/RaBundle/Resources/config/security.yml
- src/Surfnet/StepupRa/RaBundle/Security/Authorization/Context/InstitutionContext.php
- src/Surfnet/StepupRa/RaBundle/Security/Authorization/Voter/AllowedInOtherInstitutionVoter.php
- src/Surfnet/StepupRa/RaBundle/Service/InstitutionConfigurationOptionsService.php
- src/Surfnet/StepupRa/RaBundle/Service/InstitutionConfigurationOptionsServiceInterface.php
- src/Surfnet/StepupRa/RaBundle/Tests/Security/Authorization/Voter/AllowedInOtherInstitutionVoterTest.php
The voter for now only tests if the logged in user is allowed to
VIEW_AUDITLOG. Other authorizations can be added to this voter if the
context is 'allowed in other institutions'.
The vote method body might need to be revised at that point. But for
now this tests all the appropriate authorization related checks.
> Create and test the AllowedInOtherInstitutionVoter

- src/Surfnet/StepupRa/RaBundle/Controller/VettingController.php
- src/Surfnet/StepupRa/RaBundle/Service/SecondFactorService.php
The actor id is used to test in MW, if the actor is a SRAA. If the user
is SRAA, then it is allowed to vet tokens of any institution. If the
user is not SRAA, then FGA options are taken into account.
For now this additional SRAA context is required when starting the
vetting procedure.
See https://www.pivotaltracker.com/story/show/160283514
> Pass the actor id when starting vetting procedure

- src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less
- src/Surfnet/StepupRa/RaBundle/Resources/views/RaManagement/manage.html.twig
- src/Surfnet/StepupRa/RaBundle/Resources/views/RaManagement/raCandidateOverview.html.twig
- src/Surfnet/StepupRa/RaBundle/Resources/views/SecondFactor/auditLog.html.twig
- src/Surfnet/StepupRa/RaBundle/Resources/views/SecondFactor/search.html.twig
This feature is broken, as middleware does not acknowledge and implement
the sorting on the document number.
Adding support for this might be taken up at a later stage and is
requested in this chore:
https://www.pivotaltracker.com/story/show/161310060
> Disable sorting on document number

- app/Resources/translations/messages.en_GB.xliff
- app/Resources/translations/messages.nl_NL.xliff
- app/Resources/translations/validators.en_GB.xliff
- app/Resources/translations/validators.nl_NL.xliff
- src/Surfnet/StepupRa/RaBundle/Command/ChangeRaManagementInstitutionCommand.php
- src/Surfnet/StepupRa/RaBundle/Controller/RaManagementController.php
- src/Surfnet/StepupRa/RaBundle/Form/Type/ChangeRaManagementInstitutionType.php
- src/Surfnet/StepupRa/RaBundle/Resources/config/routing.yml
- src/Surfnet/StepupRa/RaBundle/Resources/public/js/stepup-ra.js
- src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less
- src/Surfnet/StepupRa/RaBundle/Resources/views/RaManagement/manage.html.twig
- src/Surfnet/StepupRa/RaBundle/Security/Authentication/Token/SamlToken.php
- src/Surfnet/StepupRa/RaBundle/Service/InstitutionConfigurationOptionsService.php
The RAA can switch to an institution he/she will be accrediting a RA candidate on behalf of.
This institution is stored in the SamlToken and persisted between
requests.
The Ra management institution can be found on the SamlToken:
$token->getRaManagementInstitution(). This will be required when
RAAs that can promote users for other RAs is implemented in Stepup-RA.
- Less & JS have been updated -> ass:dump!
- Translations have been updated, see Pivotal for details.
See: https://www.pivotaltracker.com/story/show/160283517
>  Add possibility for RAA to switch institution

- app/Resources/translations/messages.en_GB.xliff
- app/Resources/translations/messages.nl_NL.xliff
- app/Resources/translations/validators.en_GB.xliff
- app/Resources/translations/validators.nl_NL.xliff
- app/Resources/views/base.html.twig
- src/Surfnet/StepupRa/RaBundle/Command/ChangeRaaInstitutionCommand.php
- src/Surfnet/StepupRa/RaBundle/Controller/RaaController.php
- src/Surfnet/StepupRa/RaBundle/Form/Type/RaaInstitutionSelectionType.php
- src/Surfnet/StepupRa/RaBundle/Resources/config/routing.yml
- src/Surfnet/StepupRa/RaBundle/Resources/config/security.yml
- src/Surfnet/StepupRa/RaBundle/Resources/config/services.yml
- src/Surfnet/StepupRa/RaBundle/Security/Authentication/Token/SamlToken.php
- src/Surfnet/StepupRa/RaBundle/Security/Authorization/Voter/AllowedToSwitchInstitutionVoter.php
- src/Surfnet/StepupRa/RaBundle/Service/RaListingService.php
- src/Surfnet/StepupRa/RaBundle/Tests/Security/Authentication/Token/SamlTokenTest.php
- src/Surfnet/StepupRa/RaBundle/Tests/Security/Authorization/Voter/AllowedInOtherInstitutionVoterTest.php
- src/Surfnet/StepupRa/RaBundle/Tests/Security/Authorization/Voter/AllowedToSwitchInstitutionVoterTest.php
This switcher is used by RAA users to change between the institutions
they are RAA for.
This switcher is a copy of the SRAA switcher and behaves in a similar
fashion. The difference between them is that the SRAA can switch to all
institutions, and the RAA can only switch to institutions it is actually
RAA for.
The SamlToken was updated and set with a field that stores the 'home'
institution of the RAA. This to ensure the RAA can only switch to his
own institutions.
> Add the RAA institution switcher

- src/Surfnet/StepupRa/RaBundle/Controller/RaaController.php
- src/Surfnet/StepupRa/RaBundle/Security/Authorization/Voter/AllowedToSwitchInstitutionVoter.php
- src/Surfnet/StepupRa/RaBundle/Service/RaListingService.php
- src/Surfnet/StepupRa/RaBundle/Tests/Security/Authorization/Voter/AllowedToSwitchInstitutionVoterTest.php
By filtering the ra listing on the identity id we can see which
institutions the current RA(A) is RA(A) for. If more than on result
is shown, the RAA switcher is shown.
> Determine user RA(A) institutions from ra listing

- app/Resources/translations/messages.en_GB.xliff
- app/Resources/translations/messages.nl_NL.xliff
- src/Surfnet/StepupRa/RaBundle/Resources/views/SecondFactor/auditLog.html.twig
When an ra management related auditlog entry is displayed, the ra
institution is echoed in the action text. Resulting in something like:
"Accredited as RA @ institution-a"
See: https://github.com/OpenConext/Stepup-RA/pull/181
See: https://github.com/OpenConext/Stepup-Middleware-clientbundle/pull/71
See: https://github.com/OpenConext/Stepup-Middleware/pull/253
> Display the ra institution in auditlog

- src/Surfnet/StepupRa/RaBundle/Resources/config/security.yml
- src/Surfnet/StepupRa/RaBundle/Security/Authentication/Provider/SamlProvider.php
- src/Surfnet/StepupRa/RaBundle/Security/Authentication/Token/SamlToken.php
- src/Surfnet/StepupRa/RaBundle/Tests/Security/Authentication/Token/SamlTokenTest.php
- src/Surfnet/StepupRa/RaBundle/Tests/Security/Authorization/Voter/AllowedInOtherInstitutionVoterTest.php
- src/Surfnet/StepupRa/RaBundle/Tests/Security/Authorization/Voter/AllowedToSwitchInstitutionVoterTest.php
The RA must also be able to switch to the institution it is RA for.
Previously this was only allowed for (S)RAA users via the institution
switcher. Now that the SAML provider also switches to another inst.
outside the SHO of the authenticating user, the change is authorization
was required.
>  Allow all RA roles to change the institution scope

- src/Surfnet/StepupRa/RaBundle/Security/Authentication/Provider/SamlProvider.php
- src/Surfnet/StepupRa/RaBundle/Security/Authorization/Voter/AllowedToSwitchInstitutionVoter.php
- src/Surfnet/StepupRa/RaBundle/Service/IdentityService.php
In order to ensure we can find an identity, we no longer need to pass
the institution of that identity. As the RA(A) might be RA for an
institution it does not have a SHO for.
To achieve this goal, the IdentitySearchQuery has been updated, the
Institution parameter has been made optional. This change was applied
in:
- https://github.com/OpenConext/Stepup-RA/pull/183
- https://github.com/OpenConext/Stepup-SelfService/pull/161
- https://github.com/OpenConext/Stepup-Middleware-clientbundle/pull/72
- https://github.com/OpenConext/Stepup-Middleware/pull/255
> Update authentication in order to find identities

- src/Surfnet/StepupRa/RaBundle/Controller/RaManagementController.php
- src/Surfnet/StepupRa/RaBundle/Controller/RaaController.php
- src/Surfnet/StepupRa/RaBundle/Resources/config/routing.yml
- src/Surfnet/StepupRa/RaBundle/Resources/views/RaManagement/manage.html.twig
- src/Surfnet/StepupRa/RaBundle/Security/Authentication/Provider/SamlProvider.php
- src/Surfnet/StepupRa/RaBundle/Security/Authentication/Token/SamlToken.php
- src/Surfnet/StepupRa/RaBundle/Security/Authorization/Voter/AllowedToSwitchInstitutionVoter.php
- src/Surfnet/StepupRa/RaBundle/Tests/Security/Authorization/Voter/AllowedToSwitchInstitutionVoterTest.php
The Raa switcher was removed but the RAA logic looked for the institution of the user and not the institution where a user was RAA for. So there was unexpected behavior occurring when a user was performing actions on behalf of a specific RAA institution. This should be fixed now.
> Will make the RAA logic watch for RA institution instead of user institution

- src/Surfnet/StepupRa/RaBundle/Controller/SecondFactorController.php
The token sorting was broken because of a wrongly given collection.
This commit should fix the sorting for all columns.
> Fix the token sorting

- .travis.yml
- CHANGELOG.md
- src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less
- src/Surfnet/StepupRa/RaBundle/Resources/views/SecondFactor/search.html.twig
This was already fixed for FGA (release 17) but now also backported to release 16.
The document number sorting feature is now disabled. And the header is styled appropriately. There was no option to search on the document number, so no change was required for that.
> Fix the token sorting PART II

- app/Resources/translations/messages.en_GB.xliff
- app/Resources/translations/messages.nl_NL.xliff
- app/Resources/translations/validators.en_GB.xliff
- app/Resources/translations/validators.nl_NL.xliff
- app/Resources/views/base.html.twig
- src/Surfnet/StepupRa/RaBundle/Controller/RaaController.php
- src/Surfnet/StepupRa/RaBundle/Resources/config/routing.yml
- src/Surfnet/StepupRa/RaBundle/Resources/views/InstitutionConfiguration/overview.html.twig
The institution configuration page displays the configuration settings
for the requested institution. By default this is the institution of the
logged in identity.
Translations have been added for the labels and menu entry.
https://www.pivotaltracker.com/story/show/160283525
https://github.com/OpenConext/Stepup-Deploy/wiki/rfc-fine-grained-authorization/b6852587baee698cccae7ebc922f29552420a296#configuration-info-for-the-raa
> Add an institution configuration page

- app/Resources/translations/messages.en_GB.xliff
- app/Resources/translations/messages.nl_NL.xliff
- app/Resources/translations/validators.en_GB.xliff
- app/Resources/translations/validators.nl_NL.xliff
- src/Surfnet/StepupRa/RaBundle/Resources/views/InstitutionConfiguration/overview.html.twig
- The use_ra(a) labels have been rephrased
- ~~The inverse (in which institutions do we have ra's?) has been
implemented~~ This feature was later removed as the solution that was reused wasn't robust enough. We don't have time now to create a dedicated endpoint for this feature.
- The order of the config options has been changed slightly
This PR closely relates to #195 and is part of this ticket:
https://www.pivotaltracker.com/story/show/160283525
> Refine the display of FGA institution config opts

- app/Resources/translations/messages.en_GB.xliff
- app/Resources/translations/messages.nl_NL.xliff
- app/Resources/translations/validators.en_GB.xliff
- app/Resources/translations/validators.nl_NL.xliff
- src/Surfnet/StepupRa/RaBundle/Command/SelectInstitutionCommand.php
- src/Surfnet/StepupRa/RaBundle/Controller/RaaController.php
- src/Surfnet/StepupRa/RaBundle/Form/Type/SelectInstitutionType.php
- src/Surfnet/StepupRa/RaBundle/Resources/config/routing.yml
- src/Surfnet/StepupRa/RaBundle/Resources/views/InstitutionConfiguration/overview.html.twig
A form was added with the RA listing items of the logged in RAA. If a
SRAA is on the page, the config of it's currently set SHO is displayed.
SRAA should use the SRAA switcher to view the config of another
institution.
This might be the best of the three tickets to perform a functional test on. The discussion in the pivotal ticket might prove insightful.
https://www.pivotaltracker.com/story/show/160283525
> Allow RAAs to switch between institution config

- src/Surfnet/StepupRa/RaBundle/Service/RaListingService.php
The get method of the ra listing method is missing because a new
ra listing service class was introduced.
> Add missing get method to ra listing service

- composer.lock
- src/Surfnet/StepupRa/RaBundle/Controller/RaManagementController.php
- src/Surfnet/StepupRa/RaBundle/Resources/config/routing.yml
- src/Surfnet/StepupRa/RaBundle/Service/RaListingService.php
When requesting a single ra listing the actorId was not send so
a ra could be returned while this shouldn't be allowed.
> Add actorId to ra-listing endpoint

- src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less
This prevents the text fields from becoming 100% wide, which does not
look visually attractive.
Other custom widths that where set have been left in place, except if
they matched the now set max width
Pivotal reference:
https://www.pivotaltracker.com/story/show/164244268 (task 2)
> Set maximum form text element width

- src/Surfnet/StepupRa/RaBundle/Form/Type/CreateRaType.php
- src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less
The Create Ra and cancel buttons now align horizontally and are
displayed like the other buttons. Vertically positioned under the
other form input elements.
This covers task two from this Pivotal story:
https://www.pivotaltracker.com/story/show/164244365
> Update button alignment on 'create-ra' page

- src/Surfnet/StepupRa/RaBundle/Controller/ProfileController.php
- src/Surfnet/StepupRa/RaBundle/Controller/RaaController.php
The ra switcher was removed but certain logic was still used
by the switcher on the institution configuration page.
This will also use the profile endpoint to determine the institutions
we could view the settings from.
> Fix institution switcher for ra configuration page

- src/Surfnet/StepupRa/RaBundle/Controller/RaManagementController.php
- src/Surfnet/StepupRa/RaBundle/Form/Type/CreateRaType.php
The roleAtInstitution needed to be implemented instead of the no longer existing ra institute field.
https://www.pivotaltracker.com/story/show/164400522
> Fix accredit candidate command usage

- src/Surfnet/StepupRa/RaBundle/Controller/RaManagementController.php
- src/Surfnet/StepupRa/RaBundle/Controller/SecondFactorController.php
Other controller actions use the paginator to paginate their results, sorting was broken in certain situations.
This was fixed for the token overview in #185, but not fixed for the other paginator usages.
This should fix the `UnexpectedTypeException` 'PropertyAccessor requires a graph of objects or arrays to operate on error.
https://www.pivotaltracker.com/story/show/164729675
> Apply fix from #185 to other paginate calls

- app/Resources/translations/messages.en_GB.xliff
- app/Resources/translations/messages.nl_NL.xliff
- src/Surfnet/StepupRa/RaBundle/Controller/RaLocationController.php
- src/Surfnet/StepupRa/RaBundle/Controller/RaaController.php
- src/Surfnet/StepupRa/RaBundle/Resources/config/services.yml
- src/Surfnet/StepupRa/RaBundle/Resources/public/js/stepup-ra.js
- src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less
- src/Surfnet/StepupRa/RaBundle/Service/InstitutionListingService.php
Sraa access was prevented from certain pages implementing the
institution switcher. That was happening because MW didn't
return institutions when fetching a profile from teh current user.
This is now handled by the InstitutionListingService which will
fetch all institutions.
> Fix sraa access on institution switcher pages

- src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less
The role at institution select lists are displayed in one row even
though the are two separate elements. The symfony form styling is
overridden in order to render them nicely together. For modern browsers,
flex layout is utilized. For IE10+11, a fallback is used based on the
previous solution that was in place.
See: https://www.pivotaltracker.com/story/show/165719957
> Resolve floating issue for role-at-institution form group

- .travis.yml
- CHANGELOG.md
- composer.lock
This change will apply the countermeasures to harden against CVE 2019-3465 and will effectively bump `robrichards/xmlseclibs` to version 3.0.4
Targeted at release 17 (3.0.1)
> Upgrade Stepup-saml-bundle to version 4.1.8

- .travis.yml
This is done in order to be able to test behavior on php 7.3 to
explore possible php migration issues.
> Test php 7.3 with travis

- src/Surfnet/StepupRa/RaBundle/Controller/ExceptionController.php
Exceptions thrown while not logged in are wrapped in a HttpException.
This is preventing the rendering of a sane error message for the enduser.
https://www.pivotaltracker.com/story/show/170487625
> Fix exception controller authentication exceptions

- src/Surfnet/StepupRa/RaBundle/Form/Type/AmendRegistrationAuthorityInformationType.php
- src/Surfnet/StepupRa/RaBundle/Form/Type/ChangeRaLocationType.php
- src/Surfnet/StepupRa/RaBundle/Form/Type/ChangeRaRoleType.php
- src/Surfnet/StepupRa/RaBundle/Form/Type/CreateRaLocationType.php
- src/Surfnet/StepupRa/RaBundle/Form/Type/CreateRaType.php
- src/Surfnet/StepupRa/RaBundle/Form/Type/SearchRaSecondFactorsType.php
- src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less
Buttons are aligned on the second column of the form field from left to right. This was agreed upon during the first development effor that touched alignment issues in this regard. The story this work hails from only mentions the change ra role and amend ra forms. Three other forms had similar button alginment issues. They have all been addressed in this commit.
Note that a app/console assetic:dump is required to enjoy these changes.
See: https://www.pivotaltracker.com/story/show/170487965
> Improve button-group button alignment

- src/Surfnet/StepupRa/RaBundle/Command/SearchRaCandidatesCommand.php
- src/Surfnet/StepupRa/RaBundle/Controller/RaManagementController.php
- src/Surfnet/StepupRa/RaBundle/Form/Type/SearchRaCandidatesType.php
The RA candidate selectlist filter was removed from the form. This
filter did not have much benefit for the user experience. And was
confusing as it seemingly behaved like the regular institution filter
(which previous to the middleware fix was broken).
See:
https://www.pivotaltracker.com/story/show/171512620
https://github.com/OpenConext/Stepup-Middleware/pull/297
> Remove filter from ra candidate search form

- src/Surfnet/StepupRa/RaBundle/Command/ExportRaSecondFactorsCommand.php
- src/Surfnet/StepupRa/RaBundle/Controller/SecondFactorController.php
- src/Surfnet/StepupRa/RaBundle/Form/Type/SearchRaSecondFactorsType.php
- src/Surfnet/StepupRa/RaBundle/Service/RaSecondFactorService.php
The export functionality was broken and resulted in an exception because the ActorId wasn't set correctly.
The export button is enabled and the export action itself will fail if the active user is not a RAA. A user is a RAA in the RA environment if RAA for any institution.
https://www.pivotaltracker.com/n/projects/1163646/stories/171517126
>  Repair the token export feature 

- src/Surfnet/StepupRa/RaBundle/Controller/RaManagementController.php
Use the location from the RA and do not set the current users' institution as location. Which would result in re-setting the user SHO as the RA location instead of the one set in the form.
https://www.pivotaltracker.com/story/show/171812783
> Allow updating the location of an RA

- CHANGELOG.md
- composer.json
- composer.lock
- src/Surfnet/StepupRa/RaBundle/Controller/VettingController.php
- src/Surfnet/StepupRa/RaBundle/Resources/config/services.yml
- src/Surfnet/StepupRa/RaBundle/Resources/views/translations.html.twig
- src/Surfnet/StepupRa/RaBundle/Service/VettingService.php
- src/Surfnet/StepupRa/RaBundle/VettingProcedure.php
- translations/messages.en_GB.xliff
- translations/messages.nl_NL.xliff
- translations/validators.en_GB.xliff
- translations/validators.nl_NL.xliff
**Be aware that this is build on top of #237 so this needs to be merged back first!**
This change will effectively make the the prove possession step optional. It's possible to configure the second factors which do not require that step.
https://www.pivotaltracker.com/story/show/172911922
> Make the the prove possession step optional

- composer.json
https://github.com/OpenConext/Stepup-Middleware/pull/314
I'm not shure why '*' was excluded, but it caused the new component_info was missing in the archive, and deploy failing.
> Fix files not added to root of archive

- composer.json
- composer.lock
- phpmd.xml
To avoid breaking builds until we have time to upgrade encore to version 1. For now only scan the prod dependencies. And in addition the PHP MD excludes where expanded to exclude `LongClassName` as MD was updated to version >=2.9 and the new sniffs where causing a build issue.
> Only audit prod dependencies for now

- src/Surfnet/StepupRa/RaBundle/Resources/public/less/style.less
- src/Surfnet/StepupRa/RaBundle/Resources/views/second_factor/search.html.twig
- src/Surfnet/StepupRa/RaBundle/Resources/views/translations.html.twig
- translations/messages.en_GB.xliff
- translations/messages.nl_NL.xliff
- translations/validators.en_GB.xliff
- translations/validators.nl_NL.xliff
The projections in Middleware have been updated to actually display the deprovisioned/removed user data. This data is anonymized but can still be relevant for RA users to look into.
This PR simply shows this forgotten token status in the list of second factors. And marks them visually by coloring their text in a lighter shade of grey.
See: https://www.pivotaltracker.com/story/show/181172862
> Display forgotten Second Factor tokens and their audit logs

- composer.lock
- src/Surfnet/StepupRa/RaBundle/Command/RevokeRecoveryTokenCommand.php
- src/Surfnet/StepupRa/RaBundle/Controller/RecoveryTokenController.php
- src/Surfnet/StepupRa/RaBundle/Form/Type/RevokeRecoveryTokenType.php
- src/Surfnet/StepupRa/RaBundle/Resources/config/routing.yml
- src/Surfnet/StepupRa/RaBundle/Resources/config/services.yml
- src/Surfnet/StepupRa/RaBundle/Resources/public/js/stepup-ra.js
- src/Surfnet/StepupRa/RaBundle/Resources/views/recovery_token/search.html.twig
- src/Surfnet/StepupRa/RaBundle/Service/RecoveryTokenService.php
- templates/translations.twig
- translations/messages.en_GB.xliff
- translations/messages.nl_NL.xliff
- translations/validators.en_GB.xliff
- translations/validators.nl_NL.xliff
This was a simple matter of calling the existing revoke endpoint on Middleware. Some new boilerplate was created to facilitate this in RA.
A form was added that is triggered by clicking 'continue' in the modal window. Some filthy JQuery code was copy pasted from the similar SF revocation solution. This code picks up the recovery token id, actor id and identity id (the one possessing the RT). And sets the values on the hidden revocation form.
A command was added that is filled with the form. And it contains the data required to revoke the token. This command is then posted onto the Middleware api (command endpoint) after being translated into a correct MW command in the client bundle.
Translations where updated.
https://www.pivotaltracker.com/story/show/181968091
> Implement recovery token revocation

- composer.lock
- src/Surfnet/StepupRa/RaBundle/Command/VettingTypeHintCommand.php
- src/Surfnet/StepupRa/RaBundle/Controller/VettingTypeHintController.php
- src/Surfnet/StepupRa/RaBundle/Form/Type/VettingTypeHintType.php
- src/Surfnet/StepupRa/RaBundle/Resources/config/routing.yml
- src/Surfnet/StepupRa/RaBundle/Resources/config/services.yml
- src/Surfnet/StepupRa/RaBundle/Resources/views/translations.html.twig
- src/Surfnet/StepupRa/RaBundle/Resources/views/vetting_type_hint/overview.html.twig
- src/Surfnet/StepupRa/RaBundle/Service/GlobalViewParameters.php
- src/Surfnet/StepupRa/RaBundle/Service/VettingTypeHintService.php
- src/Surfnet/StepupRa/RaBundle/Tests/Command/VettingTypeHintCommandTest.php
- templates/base.html.twig
- translations/messages.en_GB.xliff
- translations/messages.nl_NL.xliff
- translations/validators.en_GB.xliff
- translations/validators.nl_NL.xliff
An institution can have a translatable vetting type hint. This hint is displayed at the right place in the self service. A new tab was added to the RA app. Here you can choose an institution. The vetting type hint for that institution is then loaded. No formatting additions where added yet. This however is something to add later on (see [new story](https://www.pivotaltracker.com/story/show/182840207)). Users are allowed to remove a vetting type hint by simply clearing the previous entry in the textarea and saving a blank set of translations.
The available translation options follow the locales configured in the `parameters.yaml`. For now en_GB and nl_NL are configured by default. But adding/removing languages should not be any issue and do not require additional database migrations. As …
> Manage the institution specific vetting type hints

- src/Surfnet/StepupRa/RaBundle/Resources/views/institution_configuration/overview.html.twig
- translations/messages.en_GB.xliff
- translations/messages.nl_NL.xliff
- translations/validators.en_GB.xliff
- translations/validators.nl_NL.xliff
The self-vet, and self-asserted vetting types where not yet displayed on the `/institution-configuration` page. This configuration was added to the table of other options. And the explaining texts where translated to NL and EN.
@Shaky212 no relevant test coverage could be added that I could think of. I could create a behat test in `Stepup-deploy` But chances are very slim that much additional work would be beneficial.
See: https://www.pivotaltracker.com/story/show/183376863
> Display vetting types in institution overview

- src/Surfnet/StepupRa/RaBundle/Service/RaCandidateService.php
The new, third parameter was not yet passed. Yielding a 500 error on the ra candidate page
See: https://www.pivotaltracker.com/story/show/183688656
> Correctly check if LoA is satisfied

- package.json
Tests started failing since yesterday:
```
yarn install v1.22.19
info No lockfile found.
[1/4] Resolving packages...
warning @symfony/webpack-encore > webpack-dev-server > webpack-dev-middleware > memfs@3.6.0: this will be v4
[2/4] Fetching packages...
error @symfony/webpack-encore@4.5.0: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.21.2"
```
I was able to trace to issue back to a new release of webpack-encore:
https://github.com/symfony/webpack-encore/releases/tag/v4.5.0
This same issue also applies to stepup-selfservice, stepup-gateway, stepup-tiqr and stepup-azure-mfa.
Another approach may be to [raise the Node-version](https://github.com/OpenConext/OpenConext-containers/blob/main/docker/php-test-stepup/Dockerfile#L44), but I wasn't sure how …
> Fix unit tests

- translations/messages+intl-icu.en_GB.xliff
- translations/messages+intl-icu.nl_NL.xliff
Because this is not an actual translation, but a string replace in code, we keep the % sign as the placeholder.
This only goes for the challenge variable
**ICU Translation Format:**
We've switched to the ICU translation format because it supports pluralization, which is necessary for this project.
The ICU format is similar to the previous format but replaces support for pluralization (e.g., handling "1 token" versus "two tokens").
**Variable Substitution Format Change:**
In the ICU format, variables are expected to be enclosed in {} instead of the Symfony %variable% format used earlier. See https://symfony.com/doc/current/reference/formats/message_format.html
**Specific Variable Handling:**
The %challenge% variable, however, is not utilized within the translation files but is used for …
> Replace {} placeholders to %%

- bin/console
- composer.json
- config/routes/controllers.yaml
- config/services.yaml
- public/index.php
- src/Kernel.php
- src/Surfnet/StepupRa/Kernel.php
- src/Surfnet/StepupRa/RaBundle/EventListener/AuthenticatedUserListener.php
- src/Surfnet/StepupRa/RaBundle/EventListener/ExplicitSessionTimeoutListener.php
- src/Surfnet/StepupRa/RaBundle/Tests/Security/Session/SessionLifetimeGuardTest.php
- src/Surfnet/StepupRa/RaBundle/Tests/Security/Session/SessionStorageTest.php
Add listeners to replace the "old" handlers to manage cookie expiration. The values in     `session_max_absolute_lifetime:` and `session_max_relative_lifetime:` will be used to calculate expiration
> Manually expire cookies after a configured amount of time

- composer.json
- composer.lock
- config/routes.yaml
- config/routes/controllers.yaml
- src/Surfnet/StepupRa/RaBundle/Service/RecoveryTokenService.php
> Update latest dependecies

- config/services.yaml
- src/Surfnet/StepupRa/RaBundle/Security/Authentication/Handler/FailureHandler.php
See: https://www.pivotaltracker.com/story/show/188230772
See for test coverage: https://github.com/OpenConext/OpenConext-devconf/pull/16
> Show the user friendly error page on authn failure

- config/services.yaml
Bind the remote IdP setting so it can be used in the metadata endpoint.
https://github.com/OpenConext/Stepup-RA/issues/342
> Fix remote metadata endpoint
